### PR TITLE
lp port mp sale markup - rebased

### PR DESCRIPTION
**Pull request by lepistone**
This is a rebase of #3.
- I did an interactive rebase to be able to merge that, squashing 3 commits changing .travis.yml and deleting another one duplicating the dependency on sale_line_watcher (already merged).
- Now rebased on OCA/7.0

I am doing the little fix described in #3.

### CODE REVIEW

**Comment by mdietrichc2c** [comment]
:+1: thanks @lepistone

**Comment by lepistone** [comment]
@mdietrichc2c @yvaucher I did a few small improvements in the tests as I suggested in #3. It is :+1: for me now. Thanks

**Comment by yvaucher** [comment]
:+1:

**Comment by yvaucher** [comment]
This PR is an old one from LP. I merge it.

**Pull request merged**
