### PR TITLE
sale_credit_limit by Alexis de Lattre

### PR DESCRIPTION
**Pull request by rvalyi**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Is this going to be worked on?

**Comment by pedrobaeza** [comment]
As there's no answer, I close. Feel free to reopen in case there's interest.

**Comment by astirpe** [comment]
My Company needs this module for V10.
I'm ready to start to work for the porting and so I would say that this module is of interest for someone :)

Question is: was the development of the functionality completed in this module? Or do I miss something that was planned to be developed and later on abandoned?

Thanks in advance!

**Comment by pedrobaeza** [comment]
@astirpe, you should see https://github.com/OCA/partner-contact/tree/9.0/partner_financial_risk as a good replacement. There are some extensions for sale and stock parts: https://github.com/OCA/partner-contact/pull/300 and https://github.com/OCA/partner-contact/pull/295

**Pull request closed without merging**
