### PR TITLE
[ADD] sale_partner_default_journal

### PR DESCRIPTION
**Pull request by hbrunn**
Default journal for partners
============================

This module was written to make it more convenient to work with multiple
sale journals by assigning a default journal per partner.

Configuration
=============

To configure this module, you need to:

#. go to Settings / Technical / Parameters / Company properties
#. search for 'Default sale journal' and set the default for all partner
#. on a specific partner, set the field `Sale journal` in the `Accounting` tab

### CODE REVIEW

**Comment by andreschenkels** [comment]
Could you also make a purchase_partner_default_journal module to create the same configurability at the purchase side?

**Comment by andreschenkels** [comment]
:+1:  works like a charm

**Review by susport — APPROVED** [review]
Okay, good 👍

**Review by gurneyalex — APPROVED** [review]

**Comment by hbrunn** [comment]
closing this as I won't fix the tests

**Pull request closed without merging**
